version: '3.7'

services:
  signature:
    build:
      context: .
      dockerfile: Dockerfile_signature
    image: tiktok-signature:1.0.0
    environment:
      PORT: 8080
    ports:
      - "127.0.0.1:8080:8080"

  redis:
    image: redis:alpine
    command:
      - redis-server
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    depends_on:
      - signature

  celery:
    build:
      context: .
      dockerfile: Dockerfile_celery
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - signature
      - redis
    restart: always

  flower:
    image: mher/flower
    container_name: flower
    command: celery flower --persisten=True
    env_file:
      - .env
    ports:
      - 8888:8888
    volumes:
      - flower_data:/data
    depends_on:
      - celery

  postgres:
    image: postgres:16.2
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./test_data:/test_data
    ports:
      - "127.0.0.1:5432:5432"

  parserbot-bot:
    build:
      context: .
      dockerfile: Dockerfile_dj
    image: parserbot-django:latest
    env_file:
      - .env
    environment:
      DJ_DEBUG: "False"
    depends_on:
      - signature
      - redis
      - celery
      - postgres
    volumes:
      - .:/app
    command:
      - sh
      - -c
      - |
        python manage.py migrate --noinput
        python manage.py run_bot

  parserbot-admin:
    build:
      context: .
      dockerfile: Dockerfile_dj
    image: parserbot-django:latest
    ports:
      - "8000"
    volumes:
      - ./nginx-templates:/app/nginx-templates
      - nginx_static:/app/assets/
      - nginx_media:/var/www/media/
      - .:/app
    env_file:
      - .env
    environment:
      DJ_DEBUG: "True"
    depends_on:
      - parserbot-bot
    command:
      - sh
      - -c
      - |
        python manage.py collectstatic --noinput
        python manage.py runserver 0.0.0.0:8000 --noreload

  nginx:
    image: nginx
    ports:
      - '80:80'
    environment:
      UPSTREAM_SERVER: parserbot-admin:8000
      FLOWER_SERVER: flower:8888
    volumes:
      - ./nginx-templates:/etc/nginx/templates/
      - nginx_static:/var/www/static/
      - nginx_media:/var/www/media/
    depends_on:
      - parserbot-admin

volumes:
  db_data:
  nginx_media:
  nginx_static:
  flower_data: