version: '3.7'

services:
  signature:
    build:
      context: .
      dockerfile: Dockerfile_signature
    image: tiktok-signature:1.0.0
    environment:
      PORT: 8080
    ports:
      - "8080:8080"

  redis:
    image: redis:alpine
    command:
      - redis-server
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    depends_on:
      - signature

  celery:
    build:
      context: .
      dockerfile: Dockerfile_celery
    env_file:
      - dev.env
    volumes:
      - .:/app
    depends_on:
      - signature
      - redis

  flower:
    image: mher/flower
    container_name: flower
    command: celery flower --persisten=True --basic-auth="user1:password1"
    env_file:
      - dev.env
    ports:
      - 8888:8888
    volumes:
      - flower_data:/data

volumes:
  flower_data:
