FROM python:3.11
WORKDIR /app
# copy and install reqs
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --upgrade setuptools && pip install -r requirements.txt
# copy project
COPY . .
