FROM python:3.11
WORKDIR /app
# copy and install reqs
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --upgrade setuptools && pip install -r requirements.txt
RUN playwright install-deps
RUN playwright install
# copy project
COPY . .
RUN apt-get -y install `pwd`/google-chome.deb

# patch TikTokApi lib
RUN python post_install.py
