# Generated by Django 4.2.11 on 2024-04-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringlink',
            name='next_monitoring_date',
            field=models.DateTimeField(verbose_name='Дата следующего мониторинга'),
        ),
    ]
