# Generated by Django 4.2.11 on 2024-05-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='chats_id_for_alert',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='id чатов для оповещений (разделитель - запятая)'),
        ),
    ]
