# Generated by Django 4.2.11 on 2024-05-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(verbose_name='Chat id')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя')),
                ('state', models.CharField(default='NEW', max_length=50, verbose_name='Статус в переписке в боте')),
                ('last_visit_time', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего посещения')),
                ('registration_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Даты и время регистрации')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('send_alerts', models.BooleanField(default=False, verbose_name='Слать оповещения?')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
